### ISSUE TITLE
Install issues and doubts

### ISSUE THREAD

**Issue by snadal** [code-chat-br/n8n-node-codechat#2]
Hello, and thank you for this n8n module!!

I tried to use this connecting to my own instance of https://github.com/code-chat-br/whatsapp-api, but I had no luck. 

Everytime I try, I get this message:
```
NodeApiError: Cannot read properties of undefined (reading 'toString')
    at RoutingNode.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/RoutingNode.js:112:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/Workflow.js:694:23)
    at async /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:585:53
```

Also, I saw on https://docs.codechat.dev/?utm_source=n8n_app&utm_medium=node_settings_modal-credential_link&utm_campaign=n8n-nodes-codechat.codeChat#/ that the body for most of the requests is different rom the one on whatsapp-api. Maybe should I use a different project?

Thank you again for your code.

**Comment by jrCleber** [comment]
Hi! How are you?
This **whatsapp-api** is a free version of my **CodeChat** api, developed by this organization.
Therefore, **whatsapp-api** does not yet have integration with **n8n**.
